const Q = (id, topic, level, prompt, options, answer, hints, explanation, source) => ({ id, type: "mc", topic, level, prompt, options, answer, hints, explanation, source });
const D = (id, topic, level, prompt, context, hints, rubric, model, source) => ({ id, type: "disc", topic, level, prompt, context, hints, rubric, model, source });

window.QUIZ_BANK = [
  Q("etl-padronizacao", "ETL", 1,
    "Ao reunir vendas de dois sistemas, em qual etapa você padroniza datas e remove duplicidades?",
    ["Extração", "Transformação", "Carga", "Consulta OLAP"], 1,
    ["Essa etapa ocorre depois da leitura das fontes e antes da gravação no destino.", "Ela aplica regras de limpeza, conversão e integração."],
    "A transformação limpa, converte, deduplica e concilia os dados extraídos antes da carga no destino analítico.", "Banco de Questões, questões 2 e 10"),
  Q("etl-elt", "ETL", 2,
    "Qual é a diferença central entre ETL e ELT?",
    ["No ELT não existe extração.", "No ETL a carga vem antes da extração.", "No ELT parte da transformação ocorre depois da carga no ambiente de destino.", "No ETL os dados nunca são validados."], 2,
    ["Compare a ordem das letras T e L.", "Pense em onde o processamento de transformação é executado."],
    "ETL transforma antes de carregar. ELT carrega primeiro e realiza parte das transformações no destino, que pode oferecer capacidade de processamento própria.", "Business intelligence, p. 15–16"),
  Q("etl-incremental", "ETL", 2,
    "Uma carga incremental deve priorizar quais registros?",
    ["Os incluídos ou alterados desde a última carga.", "Todos os registros históricos em cada execução.", "Somente os registros com valores nulos.", "Apenas os dados já agregados em dashboards."], 0,
    ["O objetivo é evitar reprocessar todo o histórico.", "Considere inserções, atualizações e, quando necessário, exclusões."],
    "A atualização incremental identifica mudanças na origem e processa somente os registros afetados, conforme a política de atualização do DW.", "Criação de data warehouses, p. 11; Utilização das metodologias de DW, p. 17"),
  Q("etl-integracao", "ETL", 2,
    "Por que a transformação é indispensável ao integrar duas fontes de clientes em um DW?",
    ["Porque elimina a necessidade de dimensões.", "Porque converte consultas OLAP em transações.", "Porque cada fonte deve permanecer com formatos incompatíveis.", "Porque permite padronizar códigos, formatos e significados antes da análise."], 3,
    ["Imagine que uma fonte grava UF como ‘SP’ e outra como ‘São Paulo’.", "Sem uma regra comum, a mesma categoria pode aparecer como duas categorias."],
    "A integração exige regras comuns de nomenclatura, formato, identificação e qualidade para que os dados de fontes distintas possam ser analisados juntos.", "Banco de Questões, questão 10; Utilização das metodologias de DW, p. 9"),
  Q("etl-fluxo", "ETL", 1,
    "Qual sequência representa um fluxo clássico de BI com ETL?",
    ["Dashboard → OLTP → ETL → DW", "Fontes operacionais → ETL → DW → análise/visualização", "DW → ETL → fontes operacionais → OLAP", "OLAP → carga → limpeza → origem"], 1,
    ["Comece pelo registro de uma venda.", "O dado é preparado antes de entrar no ambiente analítico."],
    "As fontes operacionais produzem os dados; o ETL os extrai, transforma e carrega; o DW os organiza para análise e visualização.", "Business intelligence, p. 14–17"),
  Q("dw-caracteristicas", "DW & BI", 1,
    "Qual conjunto descreve características clássicas de um data warehouse?",
    ["Volátil, transacional, isolado e sem histórico.", "Operacional, temporário e orientado a inserções rápidas.", "Orientado por assunto, integrado, histórico e não volátil.", "Exclusivo para documentos semiestruturados."], 2,
    ["O DW apoia análise de assuntos do negócio ao longo do tempo.", "Considere integração de fontes e preservação do histórico."],
    "Um DW organiza dados por assunto, integra fontes e mantém histórico para análises; o material também o descreve como não volátil.", "Utilização das metodologias de DW, p. 9"),
  Q("dw-datamart", "DW & BI", 1,
    "Para que serve um data mart de vendas?",
    ["Registrar cada compra no caixa em tempo real.", "Atender às análises de uma área ou assunto específico.", "Substituir toda a etapa de ETL.", "Guardar apenas arquivos sem estrutura."], 1,
    ["Ele tem escopo menor que o DW corporativo.", "Pense nas necessidades de um departamento."],
    "O data mart concentra dados analíticos de uma área, como vendas, e facilita consultas dessa comunidade de usuários.", "Utilização das metodologias de DW, p. 10"),
  Q("dw-olap", "DW & BI", 1,
    "Qual afirmação diferencia melhor data warehouse e OLAP?",
    ["O DW organiza dados para análise; OLAP explora medidas por dimensões e agregações.", "OLAP guarda os pedidos operacionais; o DW imprime relatórios.", "São exatamente o mesmo componente.", "O DW só existe quando os dados são armazenados em cubos."], 0,
    ["Separe armazenamento analítico de exploração analítica.", "Um deles é o repositório; o outro descreve o processamento das consultas."],
    "O DW reúne e organiza dados históricos integrados. OLAP é o processamento analítico que permite consultar, cruzar e agregar medidas sob diferentes perspectivas.", "Banco de Questões, questão 3; Utilização das metodologias de DW, p. 13"),
  Q("bi-diagnostica", "DW & BI", 2,
    "Um painel mostra que as vendas caíram. A equipe investiga quais regiões e campanhas explicam a queda. Que tipo de análise predomina?",
    ["Descritiva", "Preditiva", "Diagnóstica", "Prescritiva"], 2,
    ["A pergunta central é ‘por que aconteceu?’.", "A equipe busca fatores associados a um resultado já observado."],
    "A análise diagnóstica investiga os motivos de um resultado. A descritiva mostra o que ocorreu; a preditiva estima o que pode ocorrer.", "Business intelligence, p. 19–20"),
  Q("oltp-olap", "OLTP × OLAP", 1,
    "Qual atividade é típica de OLTP, e não de OLAP?",
    ["Comparar a receita anual por estado.", "Agrupar vendas por trimestre e categoria.", "Explorar um cubo por produto e tempo.", "Registrar uma compra e atualizar o estoque."], 3,
    ["Pense em operação cotidiana com escrita frequente.", "OLTP atende transações individuais do negócio."],
    "OLTP registra transações operacionais, geralmente com muitas inserções e atualizações. OLAP privilegia consultas analíticas e agregações.", "Banco de Questões, questão 8; Representação relacional versus multidimensional, p. 3"),
  Q("oltp-modelagem", "OLTP × OLAP", 2,
    "Por que um sistema OLTP costuma usar modelagem mais normalizada que um esquema estrela?",
    ["Para impedir qualquer consulta SQL.", "Para reduzir redundância e anomalias nas atualizações frequentes.", "Para criar cubos físicos automaticamente.", "Para eliminar chaves primárias."], 1,
    ["Pense no custo de inserir ou alterar um pedido.", "Dados repetidos em tabelas operacionais podem ficar inconsistentes."],
    "A normalização ajuda a manter consistência em operações frequentes de escrita. No esquema estrela, dimensões desnormalizadas simplificam consultas analíticas.", "Representação relacional versus multidimensional, p. 17–21"),
  Q("olap-rollup", "Operações OLAP", 1,
    "Um relatório mostra vendas por cidade. Você passa a ver o total por estado. Qual operação realizou?",
    ["Roll-up", "Drill-down", "Slice", "Pivot"], 0,
    ["Observe se você ganhou ou perdeu detalhe.", "A agregação subiu na hierarquia cidade → estado."],
    "Roll-up agrega dados em um nível mais alto da hierarquia. O caminho inverso, de estado para cidade, é drill-down.", "Compreender a modelagem de dados multidimensional, p. 11"),
  Q("olap-slice", "Operações OLAP", 2,
    "Ao fixar o ano em 2025 e observar as vendas por produto e região, você realiza principalmente:",
    ["Drill-down", "Roll-up", "Slice", "Carga incremental"], 2,
    ["Uma dimensão recebe um valor específico.", "Imagine selecionar uma fatia do cubo correspondente a um ano."],
    "Slice fixa um valor em uma dimensão, como ano = 2025, e observa as demais perspectivas. Dice seleciona subconjuntos ou intervalos em múltiplas dimensões.", "Compreender a modelagem de dados multidimensional, p. 11"),
  Q("olap-drilldown", "Operações OLAP", 1,
    "Você parte do total de vendas por estado e abre o detalhe por cidade. Isso é:",
    ["Pivot", "Drill-down", "Roll-up", "ETL"], 1,
    ["Agora aparecem mais linhas e mais detalhe.", "É a operação inversa de roll-up."],
    "Drill-down desce na hierarquia de uma dimensão para mostrar um nível mais detalhado.", "Compreender a modelagem de dados multidimensional, p. 11"),
  Q("olap-rolap", "Operações OLAP", 2,
    "Qual alternativa diferencia ROLAP e MOLAP?",
    ["ROLAP usa apenas arquivos de texto; MOLAP usa planilhas.", "ROLAP é operacional; MOLAP não permite agregações.", "Ambos exigem exatamente o mesmo armazenamento físico.", "ROLAP usa estruturas relacionais; MOLAP usa armazenamento multidimensional."], 3,
    ["As letras R e M indicam a estrutura usada.", "Um consulta relações; o outro organiza medidas em estruturas multidimensionais."],
    "ROLAP trabalha sobre tabelas relacionais. MOLAP organiza dados em estruturas multidimensionais para análises, frequentemente com agregações pré-calculadas.", "Utilização das metodologias de DW, p. 13–16"),
  Q("model-fato", "Modelagem", 1,
    "Em um esquema estrela de vendas, qual dado pertence naturalmente à tabela fato?",
    ["Nome do cliente", "Quantidade vendida e chave do produto", "Descrição do departamento", "Nome da cidade"], 1,
    ["A fato guarda medidas e ligações para dimensões.", "Procure um valor numérico do evento de venda e uma chave estrangeira."],
    "A tabela fato reúne medidas, como quantidade e valor, e chaves que apontam para dimensões. Nomes e descrições ficam nas dimensões.", "Representação relacional versus multidimensional, p. 18–20"),
  Q("model-dimensao", "Modelagem", 1,
    "Qual conjunto combina melhor com uma dimensão Produto?",
    ["Valor total da venda e quantidade vendida", "Chave de cliente e valor de frete", "Nome, categoria e departamento do produto", "Soma de vendas de todas as lojas"], 2,
    ["Dimensões descrevem o contexto das medidas.", "Pense em atributos usados para filtrar e agrupar vendas por produto."],
    "A dimensão Produto guarda atributos descritivos, como nome, categoria e departamento. Os valores vendidos ficam na fato.", "Representação relacional versus multidimensional, p. 20"),
  Q("model-star", "Modelagem", 2,
    "Qual é a principal diferença estrutural entre Star Schema e Snowflake Schema?",
    ["No Star, dimensões tendem a ser desnormalizadas; no Snowflake, podem ser divididas em tabelas relacionadas.", "No Star não existe tabela fato; no Snowflake existe.", "O Snowflake não permite dimensões de tempo.", "O Star só funciona em OLTP."], 0,
    ["Olhe para a organização das tabelas dimensão.", "Normalização cria tabelas auxiliares e mais relacionamentos."],
    "O Star liga dimensões normalmente desnormalizadas diretamente à fato. O Snowflake normaliza dimensões em tabelas auxiliares, reduzindo redundância e ampliando junções.", "Banco de Questões, questões 1 e 9; Representação relacional versus multidimensional, p. 17–22"),
  Q("model-grao", "Modelagem", 3,
    "Para analisar quantidade e valor por cliente, produto e dia, qual grão é mais útil para uma única fato de vendas?",
    ["Uma linha por ano da empresa", "Uma linha por item vendido em um pedido", "Uma linha por departamento, sem cliente", "Uma linha por cliente, sem data e produto"], 1,
    ["O grão é o significado de cada linha da fato.", "Você precisa preservar simultaneamente cliente, produto e data para as três análises."],
    "Uma linha por item do pedido preserva o detalhe necessário para somar valor e quantidade por cliente, produto, departamento e período.", "Banco de Questões, questão 4"),
  Q("model-sql", "Modelagem", 3,
    "Para obter a quantidade vendida por departamento e semana, quais campos devem aparecer no agrupamento?",
    ["Somente o identificador do pedido.", "Cliente e valor unitário.", "Produto e quantidade sem dimensão de tempo.", "Departamento da dimensão Produto e semana/ano da dimensão Tempo."], 3,
    ["A medida é somada; os atributos de análise entram no GROUP BY.", "Semana sozinha pode se repetir em anos diferentes."],
    "Some a quantidade da fato e agrupe por departamento da dimensão Produto e por ano + semana da dimensão Tempo.", "Banco de Questões, questão 4"),
  Q("model-joins", "Modelagem", 2,
    "Qual consequência costuma acompanhar a normalização das dimensões no Snowflake Schema?",
    ["A tabela fato deixa de armazenar medidas.", "Todas as consultas tornam-se transações OLTP.", "Menos redundância nas dimensões, mas mais junções nas consultas.", "Nenhuma dimensão pode ter hierarquia."], 2,
    ["Atributos descritivos passam para tabelas auxiliares.", "Pergunte quantas tabelas uma consulta terá de juntar."],
    "Ao separar atributos em tabelas auxiliares, o Snowflake reduz repetição, mas aumenta a complexidade e pode exigir mais junções.", "Representação relacional versus multidimensional, p. 20–22"),
  Q("med-silver", "Medalhão", 1,
    "Na arquitetura medalhão, em qual camada os dados costumam ser limpos, validados e deduplicados?",
    ["Silver", "Bronze", "Gold", "Dashboard"], 0,
    ["A primeira camada preserva os dados brutos.", "A camada intermediária eleva a qualidade antes da preparação para o negócio."],
    "Bronze recebe os dados brutos; Silver faz limpeza, validação e integração; Gold entrega dados preparados para consumo de negócio.", "Banco de Questões, questão 5; Databricks, Medallion architecture"),
  Q("med-gold", "Medalhão", 2,
    "Um resumo confiável de receita por mês e região, pronto para um painel executivo, pertence tipicamente a qual camada?",
    ["Bronze", "Gold", "Silver bruta", "OLTP"], 1,
    ["O dado já foi tratado e está organizado para o negócio.", "Essa é a camada de tabelas agregadas e produtos analíticos finais."],
    "Gold concentra dados curados para consumo de negócio, frequentemente modelados e agregados para relatórios e dashboards.", "Banco de Questões, questão 5; Databricks, Medallion architecture"),
  Q("dados-semi", "Dados", 1,
    "Qual exemplo representa melhor dados semiestruturados?",
    ["Tabela relacional com colunas fixas", "Uma fotografia sem metadados", "Áudio de uma reunião", "Documento JSON com campos nomeados, mas estrutura flexível"], 3,
    ["Há alguma estrutura explícita, mas ela não exige uma tabela rígida.", "Pense em chaves e valores que podem variar entre registros."],
    "JSON e XML são exemplos comuns de dados semiestruturados: possuem marcações ou chaves, mas podem variar de estrutura.", "Banco de Questões, questão 6; Criação de data warehouses, p. 11–12"),
  Q("dados-nao", "Dados", 1,
    "Qual exemplo é predominantemente não estruturado?",
    ["Texto livre de um e-mail de atendimento", "Tabela de vendas com colunas fixas", "JSON de pedido com chaves definidas", "Planilha com campos padronizados"], 0,
    ["Procure conteúdo sem colunas ou esquema regular para cada informação.", "O corpo de uma mensagem pode variar livremente de assunto e formato."],
    "O texto livre de um e-mail não segue um esquema tabular fixo. Uma tabela de vendas é estruturada; JSON costuma ser semiestruturado.", "Criação de data warehouses, p. 11–12"),

  D("disc-etl", "ETL", 2,
    "Explique extração, transformação e carga usando o caso de duas lojas com sistemas de vendas diferentes.",
    "Mostre por que não basta juntar os arquivos das duas lojas.",
    ["Percorra origem → preparação → destino.", "Cite ao menos uma diferença de formato ou código que precise de uma regra comum."],
    ["Extração: coleta registros das duas fontes.", "Transformação: valida, limpa, deduplica e padroniza formatos/códigos.", "Carga: grava dados preparados no DW, conforme o grão e a atualização definidos.", "Explica por que a integração evita análises inconsistentes."],
    "Extraio os registros dos sistemas das lojas. Na transformação, converto datas e moedas, padronizo códigos de produto e cliente, trato duplicidades e verifico qualidade. Depois carrego os registros resultantes no DW. Sem essa padronização, a mesma informação poderia aparecer de formas diferentes e distorcer os indicadores.",
    "Banco de Questões, questões 2 e 10; Business intelligence, p. 14–16"),
  D("disc-star", "Modelagem", 2,
    "Defina tabela fato e tabela dimensão. Depois compare Star Schema e Snowflake Schema.",
    "Uma resposta curta e precisa é suficiente.",
    ["A fato guarda o evento mensurável; as dimensões dão contexto.", "Compare como os atributos descritivos são distribuídos entre as tabelas."],
    ["Fato: medidas e chaves para as dimensões, com grão definido.", "Dimensões: atributos descritivos usados em filtros e agrupamentos.", "Star: dimensões em geral desnormalizadas ligadas diretamente à fato.", "Snowflake: dimensões normalizadas em tabelas auxiliares, com mais relações/junções."],
    "Uma fato registra medidas de um processo, como quantidade e valor vendido, e as chaves das dimensões. As dimensões descrevem quem, o quê, quando e onde. No Star Schema, as dimensões ficam geralmente desnormalizadas e ligadas à fato. No Snowflake, seus atributos são distribuídos em tabelas normalizadas, reduzindo repetição e aumentando as junções.",
    "Banco de Questões, questões 1 e 9; Representação relacional versus multidimensional, p. 17–21"),
  D("disc-modelo", "Modelagem", 3,
    "Projete uma única fato para responder: gasto por cliente em 2025, quantidade por departamento e semana, e top 10 clientes por itens em setembro de 2025.",
    "Considere pedidos com itens, cliente, produto, data, quantidade e valor. Indique grão, medidas, dimensões e como agruparia cada indicador.",
    ["Comece pelo grão: o que representa uma linha da fato?", "Você precisará das dimensões Cliente, Produto e Tempo; Departamento pode ser atributo de Produto."],
    ["Grão: uma linha por item de pedido (ou venda de produto por cliente e data com identificador da linha).", "Fato contém chaves de Cliente, Produto e Tempo, além de quantidade e valor total do item.", "Dimensão Tempo inclui ano, mês e semana; Produto inclui departamento; Cliente identifica o comprador.", "Consultas somam valor por cliente/ano, quantidade por departamento/ano+semana e quantidade por cliente/mês, ordenando e limitando o top 10."],
    "Use FatoItemVenda(cliente_sk, produto_sk, data_sk, quantidade, valor_total_item), com grão de um item de pedido. DimCliente descreve o cliente; DimProduto inclui departamento; DimTempo inclui data, ano, mês e semana. Para 2025, some valor_total_item por cliente. Para quantidade semanal, some quantidade por departamento, ano e semana. Para setembro/2025, some quantidade por cliente, ordene decrescente e limite a 10.",
    "Banco de Questões, questão 4"),
  D("disc-oltp-olap", "OLTP × OLAP", 2,
    "Compare OLTP e OLAP na prática e explique o papel do data warehouse entre as duas atividades.",
    "Use uma compra no varejo como exemplo.",
    ["Uma atividade grava o evento; a outra resume muitos eventos.", "Mencione histórico, consultas e frequência de escrita."],
    ["OLTP registra transações do dia a dia, com escritas/atualizações frequentes.", "ETL/ELT integra e prepara dados vindos de fontes operacionais.", "O DW organiza dados históricos para análise.", "OLAP consulta e agrega medidas em diferentes dimensões."],
    "No OLTP, a loja registra cada compra e atualiza o estoque. Um processo de integração extrai e trata esses registros para o DW, que conserva dados históricos preparados. No OLAP, analistas consultam vendas por mês, região ou produto e fazem agregações para apoiar decisões.",
    "Banco de Questões, questões 3, 8 e 11; Criação de data warehouses, p. 19"),
  D("disc-medalhao", "Medalhão", 2,
    "Explique as camadas Bronze, Silver e Gold da arquitetura medalhão com um exemplo de vendas.",
    "Diga o que muda na qualidade e na finalidade dos dados de uma camada para outra.",
    ["A primeira camada mantém os registros próximos da origem.", "A última oferece indicadores e tabelas preparados para usuários de negócio."],
    ["Bronze: ingestão e preservação de registros brutos.", "Silver: validação, limpeza, padronização, deduplicação e integração.", "Gold: dados curados/modelados e agregados para consumo analítico.", "Mostra o aumento progressivo de qualidade e utilidade."],
    "Bronze recebe as vendas brutas dos sistemas, preservando-as para rastreabilidade e reprocessamento. Silver corrige formatos, valida valores, remove duplicatas e integra lojas. Gold oferece fatos, dimensões ou resumos como receita mensal por região para dashboards e decisões.",
    "Banco de Questões, questão 5; Databricks, Medallion architecture"),
  D("disc-bi", "DW & BI", 2,
    "Descreva uma arquitetura simples de BI, desde as fontes até a decisão de um gestor.",
    "Você pode representar o fluxo com setas e uma frase para cada etapa.",
    ["Comece em sistemas operacionais, planilhas ou canais digitais.", "Passe por integração, armazenamento analítico e visualização."],
    ["Fontes geram dados operacionais.", "ETL/ELT extrai, limpa, integra e padroniza.", "DW e/ou data marts organizam dados históricos para análise.", "OLAP/consultas calculam indicadores; relatórios/dashboards apresentam resultados para decisões."],
    "Fontes (vendas, estoque e atendimento) → ETL/ELT (coleta, validação e padronização) → DW/data marts (dados integrados e históricos) → consultas OLAP/indicadores → relatórios e dashboards → decisão do gestor. Governança e definições comuns mantêm os indicadores confiáveis.",
    "Banco de Questões, questão 7; Business intelligence, p. 14–18"),
  D("disc-dados", "Dados", 1,
    "Diferencie dados estruturados, semiestruturados e não estruturados, com um exemplo de cada.",
    "Explique a presença ou ausência de um esquema de campos.",
    ["Pense em tabela, documento com chaves e texto livre.", "A diferença está no grau de estrutura previsível para os campos."],
    ["Estruturado: esquema fixo, como tabela relacional de vendas.", "Semiestruturado: organização por chaves/marcações, como JSON ou XML, com esquema flexível.", "Não estruturado: sem campos regulares, como texto livre, áudio ou imagem."],
    "Uma tabela de vendas com colunas fixas é estruturada. Um pedido em JSON, com chaves nomeadas e estrutura flexível, é semiestruturado. O corpo livre de um e-mail ou uma gravação de áudio é não estruturado.",
    "Banco de Questões, questão 6; Criação de data warehouses, p. 11–12"),
  D("disc-olap-operacoes", "Operações OLAP", 2,
    "Explique roll-up, drill-down e slice em um cubo de vendas por produto, região e tempo.",
    "Dê um exemplo concreto para cada operação.",
    ["Duas operações alteram o nível de detalhe; uma seleciona uma fatia.", "Use cidade/estado e ano para montar seus exemplos."],
    ["Roll-up agrega para nível mais alto, como cidade → estado.", "Drill-down detalha, como estado → cidade.", "Slice fixa um valor de dimensão, como ano = 2025.", "Exemplos mantêm uma medida clara, como valor vendido."],
    "Roll-up soma vendas das cidades para obter totais por estado. Drill-down abre o total de um estado para mostrar suas cidades. Slice fixa ano = 2025 e examina vendas por produto e região nessa fatia do cubo.",
    "Compreender a modelagem de dados multidimensional, p. 11")
];

